@startuml

title __BLOCKS's Class Diagram__\n

  namespace org.block {
    class org.block.Blocks {
    }
    namespace network {
      class org.block.network.ConnectionInfo {
      }
      enum ConnectionMeans {
      }
      namespace client {
        class org.block.network.client.ClientConnection {
        }
      }
      namespace common {
        abstract class org.block.network.common.AbstractConnection {
        }
        interface org.block.network.common.Connection {
        }
        namespace packets {
          interface org.block.network.common.packets.Packet {
          }
        }
        namespace packets {
          interface org.block.network.common.packets.PacketValue {
          }
          namespace request {
            class org.block.network.common.packets.request.RequestConnectionPacket {
            }
            class org.block.network.common.packets.request.RequestJoinConnectionPacketBuilder {
            }
            class org.block.network.common.packets.request.RequestPacketValue {
            }
          }
          namespace verify {
            class org.block.network.common.packets.verify.VerifyConnectionPacket {
            }
            class org.block.network.common.packets.verify.VerifyConnectionPacketBuilder {
            }
          }
        }
      }
      namespace server {
        class org.block.network.server.ServerClientInfo {
        }
        class org.block.network.server.ServerConnection {
        }
      }
    }
    namespace plugin {
      interface org.block.plugin.Plugin {
      }
      class org.block.plugin.PluginContainer {
      }
      class org.block.plugin.PluginContainers {
      }
      namespace event {
        interface org.block.plugin.event.Event {
        }
        interface org.block.plugin.event.EventListener {
        }
      }
      namespace launch {
        interface org.block.plugin.launch.LaunchEvent {
        }
        interface org.block.plugin.launch.LaunchListener {
        }
        namespace event {
          class org.block.plugin.launch.event.ModuleRegisterEvent {
          }
        }
        namespace meta {
          interface org.block.plugin.launch.meta.Author {
          }
          interface org.block.plugin.launch.meta.Dependent {
          }
          interface org.block.plugin.launch.meta.Inject {
          }
          enum InjectData {
          }
        }
      }
      namespace standard {
        class org.block.plugin.standard.OpenBlockModule {
        }
        class org.block.plugin.standard.OpenBlockPlugin {
        }
        class org.block.plugin.standard.OpenBlockProject {
        }
        namespace panel {
          class org.block.plugin.standard.panel.OpenBlockNewPanel {
          }
        }
      }
    }
    namespace project.block {
      abstract class org.block.project.block.AbstractBlock {
      }
      interface org.block.project.block.Block {
      }
      interface org.block.project.block.BlockType {
      }
      interface org.block.project.block.Shapes {
      }
      namespace assists {
        abstract class org.block.project.block.assists.AbstractAttachable {
        }
        abstract class org.block.project.block.assists.AbstractBlockList {
        }
        abstract class org.block.project.block.assists.AbstractSingleBlockList {
        }
        abstract class org.block.project.block.assists.AbstractText {
        }
        interface org.block.project.block.assists.BlockList {
        }
      }
      namespace event {
        interface org.block.project.block.event.BlockEvent {
        }
        namespace mouse {
          class org.block.project.block.event.mouse.BlockMouseClickEvent {
          }
          interface org.block.project.block.event.mouse.BlockMouseEvent {
          }
        }
      }
      namespace input {
        class org.block.project.block.input.OpenBlockDialog {
        }
        class org.block.project.block.input.PanelDialog {
        }
        namespace type {
          class org.block.project.block.input.type.CharDialog {
          }
          class org.block.project.block.input.type.CollectionDialog {
          }
          class org.block.project.block.input.type.DecimalNumberDialog {
          }
          class org.block.project.block.input.type.StringDialog {
          }
          interface org.block.project.block.input.type.ValueDialog {
          }
          abstract class org.block.project.block.input.type.WholeNumberDialog {
          }
        }
      }
      namespace java{
        namespace operation {
          abstract class org.block.project.block.java.operation.AbstractNumberOperation {
          }
          class org.block.project.block.java.operation.MinusOperation {
          }
          class org.block.project.block.java.operation.SumOperation {
          }
        }
        namespace start.method {
          class org.block.project.block.java.start.method.MethodBlock {
          }
        }
        namespace value {
          abstract class org.block.project.block.java.value.AbstractValue {
          }
          class org.block.project.block.java.value.BooleanBlock {
          }
          class org.block.project.block.java.value.StringBlock {
          namespace number {
            class org.block.project.block.java.value.number.IntegerBlock {
            }
            abstract class org.block.project.block.java.value.number.NumberBlock {
            }
        }
        namespace variable {
          class org.block.project.block.java.variable.UseVariableBlock {
          }
          class org.block.project.block.java.variable.VariableBlock {
          }
        }
      }
    }
    namespace project {
      namespace context {
        class org.block.project.context.DragContext {
        }
      }
      namespace exception {
        class org.block.project.exception.InvalidBlockException {
        }
      }
      namespace module {
        interface org.block.project.module.Module {
        }
        namespace project {
          interface org.block.project.module.project.Project {
          }
          class org.block.project.module.project.UnloadedProject {
          }
        }
      }
      namespace panel {
        class org.block.project.panel.ProjectsPanel {
        }
        namespace inproject {
          class org.block.project.panel.inproject.BlockDisplayPanel {
          }
          class org.block.project.panel.inproject.ChooserDisplayPanel {
          }
          class org.block.project.panel.inproject.MainDisplayPanel {
          }
          class org.block.project.panel.inproject.Toolbar {
          }
        }
      }
      namespace section {
        class org.block.project.section.BlockSection {
        }
        interface org.block.project.section.GUISection {
        }
        class org.block.project.section.GroupedSection {
        }
        class org.block.project.section.SpecificSection {
        }
      }
    }
    namespace serialization {
      interface org.block.serialization.ConfigImplementation {
      }
      interface org.block.serialization.ConfigNode {
      }
      class org.block.serialization.FixedTitle {
      }
      namespace json {
        class org.block.serialization.json.JSONArrayConfigNode {
        }
        class org.block.serialization.json.JSONConfigImplementation {
        }
        class org.block.serialization.json.JSONConfigNode {
        }
      }
      namespace parse {
        interface org.block.serialization.parse.Deserialize {
        }
        interface org.block.serialization.parse.Parser {
        }
        interface org.block.serialization.parse.Serialize {
        }
      }
    }
    namespace util {
      class org.block.util.BlockUtils {
      }
      class org.block.util.ClassCompare {
      }
      interface org.block.util.GeneralUntil {
      }
      class org.block.util.MapBuilder {
      }
      interface org.block.util.ReflectProcessor {
      }
      namespace functions {
        interface org.block.util.functions.Getter {
        }
      }
    }
  }
  

  org.block.Blocks o-- org.block.project.module.project.Project.Loaded : loadedProject
  org.block.Blocks o-- org.block.plugin.PluginContainers : plugins
  org.block.network.client.ClientConnection -up-|> org.block.network.common.AbstractConnection
  org.block.network.common.AbstractConnection .up.|> org.block.network.common.Connection.Direct
  org.block.network.common.packets.request.RequestConnectionPacket .up.|> org.block.network.common.packets.Packet
  org.block.network.common.packets.request.RequestJoinConnectionPacketBuilder .up.|> org.block.network.common.packets.Packet.PacketBuilder
  org.block.network.common.packets.request.RequestPacketValue .up.|> org.block.network.common.packets.PacketValue
  org.block.network.common.packets.verify.VerifyConnectionPacket .up.|> org.block.network.common.packets.Packet
  org.block.network.common.packets.verify.VerifyConnectionPacketBuilder .up.|> org.block.network.common.packets.Packet.PacketBuilder
  org.block.network.server.ServerClientInfo -up-|> org.block.network.common.AbstractConnection
  org.block.network.server.ServerClientInfo o-- org.block.network.server.ServerConnection : connection
  org.block.network.server.ServerConnection .up.|> org.block.network.common.Connection
  org.block.plugin.PluginContainer .up.|> java.lang.Comparable
  org.block.plugin.PluginContainers -up-|> java.util.TreeSet
  org.block.plugin.launch.event.ModuleRegisterEvent .up.|> org.block.plugin.launch.LaunchEvent
  org.block.plugin.standard.OpenBlockModule .up.|> org.block.project.module.Module
  org.block.plugin.standard.OpenBlockProject .up.|> org.block.project.module.project.Project.Loaded
  org.block.plugin.standard.OpenBlockProject o-- org.block.project.panel.inproject.MainDisplayPanel : panel
  org.block.plugin.standard.OpenBlockProject o-- org.block.project.panel.inproject.Toolbar : toolbar
  org.block.plugin.standard.panel.OpenBlockNewPanel -up-|> javax.swing.JPanel
  org.block.project.block.AbstractBlock .up.|> org.block.project.block.Block
  org.block.project.block.AbstractBlock o-- org.block.project.block.Block.AttachableBlock : attachedTo
  org.block.project.block.assists.AbstractAttachable .up.|> org.block.project.block.Block.AttachableBlock
  org.block.project.block.assists.AbstractAttachable -up-|> org.block.project.block.AbstractBlock
  org.block.project.block.assists.AbstractBlockList .up.|> org.block.project.block.assists.BlockList
  org.block.project.block.assists.AbstractSingleBlockList .up.|> org.block.project.block.assists.BlockList.Single
  org.block.project.block.assists.AbstractSingleBlockList o-- T : value
  org.block.project.block.assists.AbstractText .up.|> org.block.project.block.Block.TextBlock
  org.block.project.block.assists.AbstractText -up-|> org.block.project.block.AbstractBlock
  org.block.project.block.event.mouse.BlockMouseClickEvent .up.|> org.block.project.block.event.mouse.BlockMouseEvent.Button
  org.block.project.block.event.mouse.BlockMouseClickEvent o-- org.block.project.block.Block : clicked
  org.block.project.block.input.OpenBlockDialog -up-|> javax.swing.JDialog
  org.block.project.block.input.PanelDialog -up-|> javax.swing.JPanel
  org.block.project.block.input.type.CharDialog .up.|> org.block.project.block.input.type.ValueDialog
  org.block.project.block.input.type.CharDialog -up-|> org.block.project.block.input.PanelDialog
  org.block.project.block.input.type.CollectionDialog .up.|> org.block.project.block.input.type.ValueDialog
  org.block.project.block.input.type.CollectionDialog -up-|> org.block.project.block.input.PanelDialog
  org.block.project.block.input.type.DecimalNumberDialog .up.|> org.block.project.block.input.type.ValueDialog
  org.block.project.block.input.type.DecimalNumberDialog -up-|> org.block.project.block.input.PanelDialog
  org.block.project.block.input.type.StringDialog .up.|> org.block.project.block.input.type.ValueDialog
  org.block.project.block.input.type.StringDialog -up-|> org.block.project.block.input.PanelDialog
  org.block.project.block.input.type.WholeNumberDialog .up.|> org.block.project.block.input.type.ValueDialog
  org.block.project.block.input.type.WholeNumberDialog -up-|> org.block.project.block.input.PanelDialog
  org.block.project.block.java.operation.AbstractNumberOperation .up.|> org.block.project.block.Block.TextBlock
  org.block.project.block.java.operation.AbstractNumberOperation .up.|> org.block.project.block.Block.ValueBlock
  org.block.project.block.java.operation.AbstractNumberOperation -up-|> org.block.project.block.assists.AbstractAttachable
  org.block.project.block.java.operation.MinusOperation -up-|> org.block.project.block.java.operation.AbstractNumberOperation
  org.block.project.block.java.operation.SumOperation -up-|> org.block.project.block.java.operation.AbstractNumberOperation
  org.block.project.block.java.start.method.MethodBlock .up.|> org.block.project.block.Block.CalledBlock.CodeStartBlock
  org.block.project.block.java.start.method.MethodBlock .up.|> org.block.project.block.Block.SpecificSectionBlock
  org.block.project.block.java.start.method.MethodBlock -up-|> org.block.project.block.assists.AbstractAttachable
  org.block.project.block.java.value.AbstractValue .up.|> org.block.project.block.Block.TextBlock
  org.block.project.block.java.value.AbstractValue .up.|> org.block.project.block.Block.ValueBlock.ConnectedValueBlock
  org.block.project.block.java.value.AbstractValue -up-|> org.block.project.block.AbstractBlock
  org.block.project.block.java.value.AbstractValue o-- V : value
  org.block.project.block.java.value.BooleanBlock -up-|> org.block.project.block.java.value.AbstractValue
  org.block.project.block.java.value.StringBlock .up.|> org.block.project.block.Block.ValueBlock.ConnectedValueBlock.MutableConnectedValueBlock
  org.block.project.block.java.value.StringBlock -up-|> org.block.project.block.java.value.AbstractValue
  org.block.project.block.java.value.number.IntegerBlock -up-|> org.block.project.block.java.value.number.NumberBlock
  org.block.project.block.java.value.number.NumberBlock .up.|> org.block.project.block.Block.ValueBlock.ConnectedValueBlock.MutableConnectedValueBlock
  org.block.project.block.java.value.number.NumberBlock -up-|> org.block.project.block.java.value.AbstractValue
  org.block.project.block.java.variable.UseVariableBlock .up.|> org.block.project.block.Block.LinkedBlock
  org.block.project.block.java.variable.UseVariableBlock .up.|> org.block.project.block.Block.SpecificSectionBlock
  org.block.project.block.java.variable.UseVariableBlock .up.|> org.block.project.block.Block.ValueBlock
  org.block.project.block.java.variable.UseVariableBlock -up-|> org.block.project.block.assists.AbstractAttachable
  org.block.project.block.java.variable.VariableBlock .up.|> org.block.project.block.Block.SpecificSectionBlock
  org.block.project.block.java.variable.VariableBlock -up-|> org.block.project.block.assists.AbstractAttachable
  org.block.project.context.DragContext o-- org.block.project.block.Block : attached
  org.block.project.context.DragContext o-- org.block.project.block.Block : dragging
  org.block.project.exception.InvalidBlockException -up-|> java.io.IOException
  org.block.project.exception.InvalidBlockException o-- org.block.project.block.Block : block
  org.block.project.module.project.UnloadedProject .up.|> org.block.project.module.project.Project
  org.block.project.module.project.UnloadedProject o-- org.block.project.module.Module : tempModule
  org.block.project.panel.ProjectsPanel -up-|> javax.swing.JPanel
  org.block.project.panel.ProjectsPanel o-- org.block.project.panel.ProjectsPanel.Search : searchingThread
  org.block.project.panel.ProjectsPanel o-- org.block.project.module.project.UnloadedProject : selected
  org.block.project.panel.inproject.BlockDisplayPanel -up-|> javax.swing.JPanel
  org.block.project.panel.inproject.BlockDisplayPanel o-- org.block.project.context.DragContext : context
  org.block.project.panel.inproject.ChooserDisplayPanel -up-|> javax.swing.JPanel
  org.block.project.panel.inproject.MainDisplayPanel -up-|> javax.swing.JPanel
  org.block.project.panel.inproject.MainDisplayPanel o-- org.block.project.panel.inproject.BlockDisplayPanel : block
  org.block.project.panel.inproject.MainDisplayPanel o-- org.block.project.panel.inproject.ChooserDisplayPanel : chooser
  org.block.project.panel.inproject.Toolbar -up-|> javax.swing.JMenuBar
  org.block.project.section.BlockSection .up.|> org.block.project.section.GUISection
  org.block.project.section.BlockSection -up-|> javax.swing.JPanel
  org.block.project.section.BlockSection o-- org.block.project.section.BlockSection.BlockPanel : panel
  org.block.project.section.BlockSection o-- org.block.project.section.GUISection : parent
  org.block.project.section.GroupedSection .up.|> org.block.project.section.GUISection
  org.block.project.section.GroupedSection -up-|> javax.swing.JPanel
  org.block.project.section.GroupedSection o-- org.block.project.section.GUISection : parent
  org.block.project.section.SpecificSection -up-|> org.block.project.section.GroupedSection
  org.block.serialization.json.JSONArrayConfigNode .up.|> org.block.serialization.ConfigNode
  org.block.serialization.json.JSONConfigImplementation .up.|> org.block.serialization.ConfigImplementation
  org.block.serialization.json.JSONConfigNode .up.|> org.block.serialization.ConfigNode

@enduml
