@startuml

title __PROJECT's Class Diagram__\n

  namespace org.block {
    namespace project.module {
      namespace project {
        interface org.block.project.module.project.Project {
            {static} + CONFIG_MODULE : FixedTitle<Module>
            {static} + CONFIG_MODULE_VERSION : FixedTitle<String>
            {static} + CONFIG_PROJECT_NAME : FixedTitle<String>
            {static} + CONFIG_PROJECT_VERSION : Listable<String>
            {static} + CONFIG_PROJECT_WINDOW_DISPLAY : FixedTitle<Integer>
            {static} + CONFIG_PROJECT_WINDOW_LOCATION : FixedTitle<Rectangle>
            {abstract} + getDirectory()
            + getDisplayName()
            + getExpectedModule()
            + getFile()
            + getPreferredGraphicsDevice()
            + getPreferredSize()
        }
      }
    }
  }
  

  namespace org.block {
    namespace project.module {
      namespace project {
        interface org.block.project.module.project.Project.Loaded {
            {abstract} + getModule()
            {abstract} + getPanel()
            {abstract} + getToolbar()
        }
      }
    }
  }
  

  namespace org.block {
    namespace project.module {
      namespace project {
        class org.block.project.module.project.UnloadedProject {
            - path : File
            - tempName : String
            - tempVersions : TreeSet<String>
            + UnloadedProject()
            + addTempVersions()
            + addTempVersions()
            + getDirectory()
            + load()
            + load()
            + saveTempData()
            + setTempModule()
            + setTempName()
        }
      }
    }
  }
  

  org.block.project.module.project.Project +-down- org.block.project.module.project.Project.Loaded
  org.block.project.module.project.UnloadedProject .up.|> org.block.project.module.project.Project
  org.block.project.module.project.UnloadedProject o-- org.block.project.module.Module : tempModule


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
